  version: '3.8'

  services:
    app:
      build:
        context: .
        dockerfile: docker/app/Dockerfile
      container_name: logistics_app
      volumes:
        - .:/var/www
      env_file:
        - .env
      networks:
        - lumen_network

    webserver:
      image: nginx:latest
      container_name: lumen_nginx
      ports:
        - "80:80"
      volumes:
        - .:/var/www
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - app
      networks:
        - lumen_network

    redis:
      image: redis:latest
      container_name: lumen_redis
      ports:
        - "6379:6379"
      networks:
        - lumen_network

  networks:
    lumen_network:
      driver: bridge
